# -*- coding: utf-8 -*-
"""Proyecto Mineria de Datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1leYuO4M3GceqJKnSlTRxSH91L-Jtsmcf

# Proyecto	Final
##Cáncer	cervical	(Factores	de	Riesgo)

####Mineria de Datos 1908
#####Integrantes del Equipo:
######Arenas Reyes Cralos Ulises
######Marmolejo Mendoza Persival
######Moran Sanchez Gerardo Jasel
######Simon Cruz Humberto

link: https://colab.research.google.com/drive/1leYuO4M3GceqJKnSlTRxSH91L-Jtsmcf?usp=sharing
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from scipy.stats import zscore
from sklearn.model_selection import train_test_split

from sklearn.datasets import fetch_openml
from sklearn.metrics import (
    f1_score,
    accuracy_score,
    recall_score,
    precision_score,
    confusion_matrix,
    roc_auc_score,
    ConfusionMatrixDisplay,
    classification_report,
    precision_recall_curve
)
from sklearn.tree import DecisionTreeClassifier # árbol de decisión para clasificación
from sklearn import tree
from sklearn.model_selection import cross_validate, cross_val_score
from sklearn.model_selection import KFold


import warnings
warnings.filterwarnings("ignore")
# %matplotlib inline

import matplotlib.pylab as plt
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture
#from sklearn_extra.cluster import KMedoids
from sklearn.metrics import silhouette_score

#Carga del dataset
dfOr = pd.read_csv('risk_factors_cervical_cancer.csv')
df = dfOr.copy()
df

"""#Análisis	Exploratorio	de	Datos	(EDA):

##Resumen	estadístico
"""

variables_numericas = ['Age','Number of sexual partners','First sexual intercourse','Num of pregnancies','Smokes (years)','Smokes (packs/year)','Hormonal Contraceptives (years)','IUD (years)','STDs (number)','STDs: Number of diagnosis','STDs: Time since first diagnosis','STDs: Time since last diagnosis']
Variables_objetivo = ['Hinselmann','Schiller','Citology','Biopsy']
variables_categoricas_NoObj = list(set(df.columns) - set(variables_numericas) - set(Variables_objetivo))
variables_categoricas = [col for col in df.columns if col not in variables_numericas]

"""##Valores Faltantes"""

#Precencia de Valores faltantes
Valores_Faltantes = (df == '?').sum()
Valores_Faltantes

"""##Estadistica Descriptiva"""

df.replace('?', np.nan, inplace=True)
df[variables_numericas] = df[variables_numericas].astype('float64')
summary = df[variables_numericas].describe()
summary.loc['mediana'] = df[variables_numericas].median()
mode_values = df[variables_numericas].mode().iloc[0]  # .iloc[0] toma la primera moda si hay varias
summary.loc['moda'] = mode_values
#count = cantidad de datos no nulos
#mean = promedio o media
#std = desviacion standar conforme a la media
#moda = valor mas repetido
#mediana centro exacto
#rango : valor minimo y valor maximo
print(summary)

"""##Outliers"""

def find_outliers_iqr(df):
    outliers = {}
    for col in df:  # Solo columnas numéricas
        Q1 = df[col].quantile(0.25)  # Primer cuartil (25%)
        Q3 = df[col].quantile(0.75)  # Tercer cuartil (75%)
        IQR = Q3 - Q1                # Rango intercuartílico
        lower_bound = Q1 - 1.5 * IQR # Límite inferior
        upper_bound = Q3 + 1.5 * IQR # Límite superior

        # Identificar valores fuera de los límites
        outliers[col] = df[(df[col] < lower_bound) | (df[col] > upper_bound)][col]

    return outliers

# Detectar outliers
outliers = find_outliers_iqr(df[variables_numericas])

# Mostrar los resultados
for col, values in outliers.items():
    print(f"Outliers en {col}:")
    print(values, "\n")

"""##Categorias unicas"""

df[variables_categoricas]
print (df[variables_categoricas].value_counts())

"""#Visualización	de	datos

##Histogramas y diagramas de caja
"""

#Histogramas
for v in variables_numericas:
   plt.figure(figsize=(15,7))
   sns.histplot(df[v], kde=True, bins=20)
   plt.title(f"Histograma de {v}")
   plt.show()

#Diagrama de caja
for v in variables_numericas:
  plt.figure(figsize=(15,7))
  sns.boxplot(x = df[v])
  plt.title(f"Boxplot de {v}")
  plt.show()

"""##Grafico de barras"""

#   Grafico de Barras para variables categoricas
for v in variables_categoricas:
    print(f"frecuencia de {v}")
    print(df[v].value_counts())
    plt.figure(figsize=(15,7))
    sns.countplot(x=v,data=df)
    plt.title(f"Distribución de {v}")
    plt.show()

#Grafica de los valores normalizados

for v in variables_categoricas:
  plt.figure(figsize= (10,6))
  #calcular porcentajes
  #SELECT sexo, Count(*) FROM
  value_counts = df[v].value_counts(normalize=True) * 100
  sns.barplot(x=value_counts.index, y=value_counts.values, palette="viridis")
  plt.title(f"Porcentaje de {v}")
  plt.xlabel(v)
  plt.ylabel("porcentaje")
  plt.show()

  #ahora mis variables son normalizados

print (df[Variables_objetivo].value_counts())
print (df[Variables_objetivo].value_counts(normalize=True) * 100)

"""##Diagramas de dispercion"""

import itertools

# Generar todas las combinaciones únicas de dos variables numéricas
combinaciones = itertools.combinations(variables_numericas, 2)
# Iterar sobre las combinaciones únicas
for b, c in combinaciones:
    for a in Variables_objetivo:
        # Crear el gráfico de dispersión
        sns.FacetGrid(df, hue=a, height=5).map(plt.scatter, b, c).add_legend()
        plt.title(f'Diagrama de dispersión: {b} vs {c} (hue={a})')

#Diagrama de dispersion
for c in variables_categoricas + ['Age']:
    if c!= Variables_objetivo:
      for a in Variables_objetivo:
        (pd.crosstab(df[c], df[a] , normalize='index')*100)\
        .plot(kind='bar', stacked=True, figsize=(12,4))
        plt.ylabel(f"Porcentaje {c}")

for c in variables_numericas:
  for a in Variables_objetivo:
    sns.FacetGrid(df, hue=a, height=5).map(sns.kdeplot, c).add_legend()

"""##Graficos de Calor"""

sns.heatmap(df[['Age', 'Number of sexual partners', 'Smokes', 'Dx:Cancer', 'Dx:CIN', 'Num of pregnancies', 'Hormonal Contraceptives (years)', 'IUD']].corr(), annot = True)
plt.title("Mapa de color de Correlación")
plt.show()

# Definir el tamaño del grupo (cantidad de variables por mapa de calor)
tamaño_grupo = 10  # Ajusta según tus necesidades
# Dividir las columnas del DataFrame en grupos
columnas = df.columns.tolist()
grupos = [columnas[i:i + tamaño_grupo] for i in range(0, len(columnas), tamaño_grupo)]
# Iterar sobre los grupos y generar un mapa de calor para cada uno
for i, grupo in enumerate(grupos):
    # Calcular la matriz de correlación para el grupo de columnas
    matriz_correlacion = df[grupo].corr()
    # Crear el mapa de calor
    plt.figure(figsize=(10, 8))
    sns.heatmap(
        matriz_correlacion,
        annot=True,
        fmt=".2f",
        cmap="coolwarm",
        cbar=True,
        square=True
    )
    plt.title(f"Mapa de Calor - Grupo {i + 1}")
    plt.tight_layout()
    plt.show()

df.corr()

"""#Implementación	de	Modelos

##Reducción	de	Dimensiones	(PCA):

###Proceso:

####1.  Normalización	de	las	características	para	garantizar	que	todas	las	variables	tengan	igual	importancia.
"""

#Reemplazar las NaN con valores de la Media (Para evitar 0.5 en variables que deben ser booleanas)
from sklearn.impute import SimpleImputer
# Usar SimpleImputer para reemplazar NaN con la media de cada columna
imputer = SimpleImputer(strategy='median')  # 'mean', 'median', 'most_frequent'
df_imputed = imputer.fit_transform(df)
# Convertir de nuevo a DataFrame
df_imputed = pd.DataFrame(df_imputed, columns=df.columns)
df_imputed

scaler = StandardScaler()
scaled_array = scaler.fit_transform(df_imputed)
scaled_df = pd.DataFrame(scaled_array, columns=df_imputed.columns)
scaled_df

"""####2. Aplicación	de	la	técnica	de	análisis	de	componentes	principales	(PCA)	para	reducir	la	dimensionalidad	del	conjunto	de	datos."""

pca = PCA()
principalComponents = pca.fit_transform(scaled_array)
df_pc= pd.DataFrame(principalComponents, columns= df.columns)
df_pc

"""###Valiadcion

####1. Varianza	explicada	acumulada	para	seleccionar	el	número	óptimo	de	componentes	principales.
"""

cov_matrix = np.cov(scaled_array.T)
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
explainded_variance = pca.explained_variance_ratio_
explainded_variance

#Visualizar la varanza explicada
plt.figure(figsize=(15,7))
bars = plt.bar(range(len(explainded_variance)), explainded_variance,
               align='center', alpha = 0.5)
plt.ylabel("Varianza explicada")
plt.xlabel("componentes principales")
plt.title("varianza explicada por cada componente principal")

for bar in bars:
  yval = bar.get_height()
  plt.text(bar.get_x() + bar.get_width()/2.0, yval, int(yval*100),
           va='bottom' if yval < 0.05 else 'top', ha='center')


labels = [str(i+1) for i in range(len(explainded_variance))]
plt.xticks(range(len(explainded_variance)), labels)
plt.show()

cumulative_variance = np.cumsum(explainded_variance)
cumulative_variance

varianza_explicada = 0.85
num_pc = np.where(cumulative_variance >= varianza_explicada) [0][0] + 1
print(f"Numero de PC que explican el {varianza_explicada*100:.0f} % de varianza es {num_pc} ")
final_pc = PCA(n_components=num_pc)
final_data = final_pc.fit_transform(scaled_array)
final_df = pd.DataFrame(final_data, columns=[f'PC_{i}' for i in range(1,num_pc+1)])
final_df

"""####2. Identificación	de	las	variables	más	importantes	contribuyentes	a	cada	componente	principal."""

cargas = pca.components_
# Mostrar las cargas de las primeras 3 componentes principales
print(pd.DataFrame(cargas[:3], columns=df.columns))

# Mostrar las 5 variables más importantes por componente principal
for i in range(17):  # Para las 17 componentes principales
    print(f"\nComponente {i+1}:")
    componentes = pd.DataFrame(cargas[i], index=df.columns, columns=['Carga'])
    componentes['Abs_Carga'] = componentes['Carga'].abs()
    componentes_sorted = componentes.sort_values(by='Abs_Carga', ascending=False)
    print(componentes_sorted.head(5))  # Mostrar las 5 variables más importantes

"""####3. Visualización	de	los	resultados	de	PCA	en	un	espacio	de	2D	o	3D	para	interpretar	la	distribución	de	los	datos	y	los	patrones	descubiertos."""

pca = PCA(n_components=3)  # Cambia n_components a 2 para una visualización en 2D
principal_components = pca.fit_transform(scaled_df)  # Asumiendo que ya tienes el DataFrame imputado
# Crear un DataFrame para las componentes principales
pca_df = pd.DataFrame(data=principal_components, columns=['PC1', 'PC2', 'PC3'])
pca_df

from mpl_toolkits.mplot3d import Axes3D
# Graficar en 3D (PC1 vs PC2 vs PC3)
fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')
ax.scatter(pca_df['PC1'], pca_df['PC2'], pca_df['PC3'], c='blue', edgecolor='k', alpha=0.7)
ax.set_title('PCA: Componentes principales 1, 2 y 3')
ax.set_xlabel('PC1')
ax.set_ylabel('PC2')
ax.set_zlabel('PC3')
plt.show()

pca = PCA(n_components=2)  # Cambia n_components a 2 para una visualización en 2D
principal_components = pca.fit_transform(scaled_df)  # Asumiendo que ya tienes el DataFrame imputado
# Crear un DataFrame para las componentes principales
pca_df_2 = pd.DataFrame(data=principal_components, columns=['PC1', 'PC2'])
pca_df_2

# Graficar en 2D (PC1 vs PC2)
plt.figure(figsize=(8, 6))
plt.scatter(pca_df_2['PC1'], pca_df['PC2'], c='blue', edgecolor='k', alpha=0.7)  # Agrega color y bordes si lo deseas
plt.title('PCA: Componentes principales 1 y 2')
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.grid(True)
plt.show()

"""##Modelo	Supervisado	(Clasificación):

###Arboles de Decision

####Incluye	preprocesamiento	de	datos	(manejo	de	valores	faltantes codificación	de variables	categóricas),	selección	de	características,	entrenamiento	del	modelo	y	ajuste	de parámetros	utilizando	técnicas	como	la	validación	cruzada.
"""

dftree = df.copy()
#dftree.loc[3, 'STDs:cervical condylomatosis'] = 1.0
#dftree.loc[3, 'STDs:AIDS'] = 1.0
reso = [col for col in dftree.columns if col not in Variables_objetivo]
X = dftree[reso]
Y = dftree['Hinselmann']
Y2 = dftree['Schiller']
Y3 = dftree['Citology']
Y4 = dftree['Biopsy']
dftree

"""###Validacion:
###Division de datos
"""

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2,stratify=Y)

X2_train, X2_test, Y2_train, Y2_test = train_test_split(X,Y2, test_size=0.2,stratify=Y2)

X3_train, X3_test, Y3_train, Y3_test = train_test_split(X,Y3, test_size=0.2,stratify=Y3)

X4_train, X4_test, Y4_train, Y4_test = train_test_split(X,Y4, test_size=0.2,stratify=Y4)

variables_categoricas_NoObj

"""###Validacion
###Metricas de rendimiento para el modelo de clasificacion
"""

##Funcion metricas
##recall verdaderos positivos entretodso
#acuracce a cuantos atine
#precision falsos positvos
def metrics_score(actual, predicted, labels=['Not Attrite', 'Attrite']):
    print(classification_report(actual, predicted))
    cm = confusion_matrix(actual, predicted)
    print(cm)
    plt.figure(figsize=(8,5))
    sns.heatmap(cm, annot=True,  fmt='.2f', xticklabels=labels, yticklabels=labels)
    plt.ylabel('Actual')
    plt.xlabel('Predicted')
    plt.show()

from sklearn.ensemble import RandomForestClassifier  # Ejemplo de modelo
from sklearn.linear_model import LogisticRegression  # Otro ejemplo de modelo

# 1. Entrena el modelo (puedes usar cualquier modelo, aquí un ejemplo)
model = RandomForestClassifier()  # Puedes cambiar a LogisticRegression() u otro modelo
model.fit(X_train, Y_train)

# 2. Realiza predicciones sobre el conjunto de prueba
Y_pred = model.predict(X_test)

# 3. Calcula métricas
accuracy = accuracy_score(Y_test, Y_pred)
recall = recall_score(Y_test, Y_pred, average='binary')  # Cambiar a 'macro' o 'weighted' si hay múltiples clases
f1 = f1_score(Y_test, Y_pred, average='binary')
precision = precision_score(Y_test, Y_pred, average='binary')

print("Accuracy:", accuracy)
print("Recall:", recall)
print("F1 Score:", f1)
print("Precision:", precision)

# 4. (Opcional) Informe completo de métricas
print("\nClassification Report:")
print(classification_report(Y_test, Y_pred))

model = RandomForestClassifier()  # Puedes cambiar a LogisticRegression() u otro modelo
model.fit(X2_train, Y2_train)

# 2. Realiza predicciones sobre el conjunto de prueba
Y2_pred = model.predict(X2_test)

# 3. Calcula métricas
accuracy = accuracy_score(Y2_test, Y2_pred)
recall = recall_score(Y2_test, Y2_pred, average='binary')  # Cambiar a 'macro' o 'weighted' si hay múltiples clases
f1 = f1_score(Y2_test, Y2_pred, average='binary')
precision = precision_score(Y2_test, Y2_pred, average='binary')

print("Accuracy:", accuracy)
print("Recall:", recall)
print("F1 Score:", f1)
print("Precision:", precision)

# 4. (Opcional) Informe completo de métricas
print("\nClassification Report:")
print(classification_report(Y2_test, Y2_pred))

model = RandomForestClassifier()  # Puedes cambiar a LogisticRegression() u otro modelo
model.fit(X3_train, Y3_train)

# 2. Realiza predicciones sobre el conjunto de prueba
Y3_pred = model.predict(X3_test)

# 3. Calcula métricas
accuracy = accuracy_score(Y3_test, Y3_pred)
recall = recall_score(Y3_test, Y3_pred, average='binary')  # Cambiar a 'macro' o 'weighted' si hay múltiples clases
f1 = f1_score(Y3_test, Y3_pred, average='binary')
precision = precision_score(Y3_test, Y3_pred, average='binary')

print("Accuracy:", accuracy)
print("Recall:", recall)
print("F1 Score:", f1)
print("Precision:", precision)

# 4. (Opcional) Informe completo de métricas
print("\nClassification Report:")
print(classification_report(Y3_test, Y3_pred))

model = RandomForestClassifier()  # Puedes cambiar a LogisticRegression() u otro modelo
model.fit(X4_train, Y4_train)

# 2. Realiza predicciones sobre el conjunto de prueba
Y4_pred = model.predict(X4_test)

# 3. Calcula métricas
accuracy = accuracy_score(Y4_test, Y4_pred)
recall = recall_score(Y4_test, Y4_pred, average='binary')  # Cambiar a 'macro' o 'weighted' si hay múltiples clases
f1 = f1_score(Y4_test, Y4_pred, average='binary')
precision = precision_score(Y4_test, Y4_pred, average='binary')

print("Accuracy:", accuracy)
print("Recall:", recall)
print("F1 Score:", f1)
print("Precision:", precision)

# 4. (Opcional) Informe completo de métricas
print("\nClassification Report:")
print(classification_report(Y4_test, Y4_pred))

#Crea el odelo de arbol de clasificacion
treeclass = DecisionTreeClassifier(max_depth=5, random_state=1)
treeclass.fit(X_train, Y_train)
#X explicativa , Y el estado que hay qe tener

#Graficar el decision tree
#gini de 0 es que ya no tiene dudas
features = list(X_train.columns)
plt.figure(figsize=[20,20])
class_name = ['absence', 'presence']
tree.plot_tree(treeclass,
               feature_names=features,
               max_depth=5,
               filled=True,
               fontsize=9,
               node_ids=True,
               class_names=class_name
               )

#Arbol 2
#Crea el odelo de arbol de clasificacion
treeclass = DecisionTreeClassifier(max_depth=5, random_state=1)
treeclass.fit(X2_train, Y2_train)
#X explicativa , Y el estado que hay qe tener

#Graficar el decision tree
#gini de 0 es que ya no tiene dudas
features = list(X2_train.columns)
plt.figure(figsize=[20,20])
class_name = ['absence', 'presence']
tree.plot_tree(treeclass,
               feature_names=features,
               max_depth=5,
               filled=True,
               fontsize=9,
               node_ids=True,
               class_names=class_name
               )

#Arbol 3
#Crea el odelo de arbol de clasificacion
treeclass = DecisionTreeClassifier(max_depth=5, random_state=1)
treeclass.fit(X3_train, Y3_train)
#X explicativa , Y el estado que hay qe tener

#Graficar el decision tree
#gini de 0 es que ya no tiene dudas
features = list(X3_train.columns)
plt.figure(figsize=[20,20])
class_name = ['absence', 'presence']
tree.plot_tree(treeclass,
               feature_names=features,
               max_depth=5,
               filled=True,
               fontsize=9,
               node_ids=True,
               class_names=class_name
               )

#Arbol 4
#Crea el odelo de arbol de clasificacion
treeclass = DecisionTreeClassifier(max_depth=5, random_state=1)
treeclass.fit(X4_train, Y4_train)
#X explicativa , Y el estado que hay qe tener

#Graficar el decision tree
#gini de 0 es que ya no tiene dudas
features = list(X4_train.columns)
plt.figure(figsize=[20,20])
class_name = ['absence', 'presence']
tree.plot_tree(treeclass,
               feature_names=features,
               max_depth=5,
               filled=True,
               fontsize=9,
               node_ids=True,
               class_names=class_name
               )

"""##Modelo	No	Supervisado	(Clustering):

###Proceso
"""

#	K-means	para	la	segmentación	de	pacientes.

#Escalado datos
#Standar scaler estandariza los datos paa tener una media de 0 y una desviacion tandar de 1
#esto se llama z-score normaizacion los valores resultantes se llaman valores
#Evitar el sesgo mejorar la convergecia compatibilidad con algoritmos de distancia
imputer = SimpleImputer(strategy='median')  # 'mean', 'median', 'most_frequent'
df_imptd = imputer.fit_transform(df)
df_imptd = pd.DataFrame(df_imptd, columns=df.columns)
df_imptd
scaler = StandardScaler()
Data_scaled_2 = pd.DataFrame(scaler.fit_transform(df_imptd), columns=df_imptd.columns)

k = 5
kmeans = KMeans(n_clusters=k,max_iter=1000, random_state=1)
kmeans.fit(Data_scaled_2)
y_kmeans = kmeans.fit_predict(Data_scaled_2)
y_kmeans

combinaciones2 = itertools.combinations(Data_scaled_2, 2)
 #Iterar sobre las combinaciones únicas
for b, c in combinaciones2:
  x_axis = b
  y_axis = c
  colores = ['purple','orange', 'green', 'blue' , 'brown', 'pink', 'gray', 'olive' ]
  for n in range(k):
            cluster = Data_scaled_2[y_kmeans == n]
            plt.scatter(cluster[x_axis], cluster[y_axis], s=100, c=colores[n], label=f'Cluster {n}')

  # Centroides
  centroids = kmeans.cluster_centers_
  plt.scatter(centroids[:, Data_scaled_2.columns.get_loc(x_axis)],
  centroids[:, Data_scaled_2.columns.get_loc(y_axis)],
  s=200, c='red', label='Centroids', alpha=0.6, edgecolors='black')

  # Etiquetas y leyenda
  plt.xlabel(x_axis)
  plt.ylabel(y_axis)
  plt.legend()
  plt.title('K-Means Clustering with K=5')
  plt.show()

# :	Normalización	de	características,	elección	del	número	de	clusters	mediante	el	método	del
#codo	y	análisis	de	los	clusters	formados	para	entender	los	segmentos	de	pacientes.

"""###Validacion
###Validacion del modelo de clustering
"""

#Grafica de codo
WCSS = {}
for kc in range(1,20):
  kmeans = KMeans(n_clusters=kc, max_iter=1000).fit(Data_scaled_2)
  WCSS[kc]= kmeans.inertia_

print(WCSS)

plt.figure()
plt.plot(list(WCSS.keys()),list(WCSS.values()), 'bx-')
plt.xlabel("Numero de clusteres")
plt.ylabel("wcss")
plt.show()

SC ={}

for ks in range(2,20):
  kmeans = KMeans(n_clusters=ks).fit(Data_scaled_2)
  labels= kmeans.predict(Data_scaled_2)
  SC[ks] = silhouette_score(Data_scaled_2, labels)

SC

plt.figure()
plt.plot(list(SC.keys()),list(SC.values()), 'bx-')
plt.xlabel("Numero de clusteres")
plt.show()

#osea que deben ser com 17 clusters

k = 17
kmeans = KMeans(n_clusters=k,max_iter=1000, random_state=1)
kmeans.fit(Data_scaled_2)
y_kmeans = kmeans.fit_predict(Data_scaled_2)
y_kmeans

y_axis = 'Age'
x_axis = 'Smokes (packs/year)'
colores = ['purple','orange', 'green', 'blue' , 'brown', 'pink', 'gray', 'olive', 'cyan', 'gold', 'lightgrey','purple','orange', 'green', 'blue' , 'brown', 'pink', 'gray', 'olive', 'cyan', 'gold', 'lightgrey','purple','orange', 'green', 'blue' , 'brown', 'pink', 'gray', 'olive', 'cyan', 'gold', 'lightgrey' ]
# Crear la gráfica de dispersión
for n in range(k):
    cluster = Data_scaled_2[y_kmeans == n]
    plt.scatter(cluster[x_axis], cluster[y_axis], s=100, c=colores[n], label=f'Cluster {n}')

# Centroides
centroids = kmeans.cluster_centers_
plt.scatter(centroids[:, Data_scaled_2.columns.get_loc(x_axis)],
            centroids[:, Data_scaled_2.columns.get_loc(y_axis)],
            s=200, c='red', label='Centroids', alpha=0.6, edgecolors='black')

# Etiquetas y leyenda
plt.xlabel(x_axis)
plt.ylabel(y_axis)
plt.legend()
plt.title('K-Means Clustering with K=17')
plt.show()